from django.contrib import admin
from django.utils.html import format_html
from .models import Signature

@admin.register(Signature)
class SignatureAdmin(admin.ModelAdmin):
    # 1. Columns shown in the list view
    list_display = ('id', 'user_name', 'signature_preview', 'feature_status', 'created_at')
    
    # 2. Filters and Search
    list_filter = ('created_at', 'user')
    search_fields = ('user__full_name', 'user__email', 'id')
    
    # 3. Read-only fields to prevent accidental vector editing
    readonly_fields = ('signature_preview_large', 'created_at', 'processed_features')

    def user_name(self, obj):
        return obj.user.full_name
    user_name.short_description = "Account Holder"

    def signature_preview(self, obj):
        """Small preview for the list table"""
        if obj.image:
            return format_html(
                '<img src="{}" style="width: 80px; height: auto; border: 1px solid #ddd; border-radius: 4px;" />',
                obj.image.url
            )
        return "No Image"
    signature_preview.short_description = "Thumbnail"

    def signature_preview_large(self, obj):
        """Large preview for the detail edit page"""
        if obj.image:
            return format_html(
                '<div style="background: white; padding: 10px; display: inline-block; border-radius: 8px;">'
                '<img src="{}" style="max-width: 400px; height: auto;" />'
                '</div>',
                obj.image.url
            )
        return "No Image"
    signature_preview_large.short_description = "Full Resolution Master"

    def feature_status(self, obj):
        """Visual check to see if ML features exist"""
        if obj.processed_features:
            count = len(obj.processed_features) if isinstance(obj.processed_features, list) else "Data"
            return format_html(
                '<span style="color: #22c55e; font-weight: bold;">● AI Vector Stored ({})</span>', 
                count
            )
        return format_html('<span style="color: #eab308; font-weight: bold;">○ Missing Features</span>')
    feature_status.short_description = "ML Status"

    # Organize the detail view layout
    fieldsets = (
        ("User Association", {
            'fields': ('user',)
        }),
        ("Visual Data", {
            'fields': ('image', 'signature_preview_large')
        }),
        ("AI Metadata", {
            'classes': ('collapse',), # Hide this section by default
            'fields': ('processed_features', 'created_at'),
            'description': "Raw 128-D vector embeddings generated by the Siamese Network."
        }),
    )